CREATE SCHEMA IF NOT EXISTS TEST;
CREATE TABLE TEST.ISSUE
(
  ID          SERIAL PRIMARY KEY,
  NAME        VARCHAR,
  DESCRIPTION VARCHAR,
  LABEL       INT
);

CREATE TABLE TEST.LABEL
(
  ID   INT PRIMARY KEY,
  NAME VARCHAR

);

INSERT INTO TEST.LABEL (ID, NAME)
VALUES (1, 'Bug');
INSERT INTO TEST.LABEL (ID, NAME)
VALUES (2, 'Documentation');
INSERT INTO TEST.LABEL (ID, NAME)
VALUES (3, 'Duplicate');
INSERT INTO TEST.LABEL (ID, NAME)
VALUES (4, 'Enhancement');
INSERT INTO TEST.LABEL (ID, NAME)
VALUES (5, 'Good First Issue');
INSERT INTO TEST.LABEL (ID, NAME)
VALUES (6, 'Help Wanted');
INSERT INTO TEST.LABEL (ID, NAME)
VALUES (7, 'Invalid');
INSERT INTO TEST.LABEL (ID, NAME)
VALUES (8, 'Question');
INSERT INTO TEST.LABEL (ID, NAME)
VALUES (9, 'Wont Fix');

ALTER TABLE TEST.ISSUE
  ADD CONSTRAINT LABEL_FK FOREIGN KEY (LABEL) REFERENCES TEST.LABEL(ID);